# Repository configs
repositories:
  # GitHub Config
  github:
    # Repository config id
    gocr-enterprise:
      name: gocr-enterprise
      owner: yyh-gl
      # If this is on enterprise, is_enterprise is true
      is_enterprise: true
      # If is_enterprise is true, you have to set this field
      enterprise_host: https://git.yyh-gl.com/api/v3
      access_token: hogehogetoken
      # ID of Slack notification destination setting
      sender: dev-team

    gocr-general:
      name: gocr
      owner: yyh-gl
      access_token: foofootoken
      slack_id: personal

# Sender configs
senders:
  # Slack notification destination configs
  slacks:
    # Sender config id
    dev-team:
      channel: pr_notification
      username: Notifier
      icon_emoji: smirk
      # Mapping of Git username and Slack username
      user_map:
        - yyh-gl:yyh_gl
      web_hook: https://hooks.slack.com/hoge/foo

    personal:
      channel: pr_notification
      username: Notifier
      icon_emoji: smile
      web_hook: https://hooks.slack.com/hoge/foo
